### ISSUE TITLE
Add precompilation support

### ISSUE THREAD

**Issue by notme1560** [ntrupin/abstractml#28]
Stumbled across this project. It looks interesting, but for a production environment I would think that it would be better to precompile or build the HTML file before sending it to the user, so it can be as fast and minimized as possible. Maybe consider adding precompilation support using the exact same files with Node to run JS from the terminal, not the browser? I can poke around when I have time and try to throw something together if you’d like.

**Comment by Yamboy1** [comment]
I've actually been considering doing this, just creating a simple node script

I'll get onto it on the next few days

**Comment by Yamboy1** [comment]
or when I get a Chance lol

**Comment by ntrupin** [comment]
I just started up the project again, and I'm working on a pre-compilation tool. I'm also giving the language a slight makeover so everything will have the ability to be nested or not, and I'll add the compiler to the repo when I finish.

**Comment by Yamboy1** [comment]
ok

**Comment by Yamboy1** [comment]
sorry I haven't been that active recently :cry:

**Comment by ntrupin** [comment]
No worries. I haven’t been active either due to exams. Life will be life, sometimes Open Source work has to be our second to what’s going on.

**Comment by Yamboy1** [comment]
Recommendation to close this as a dup of #43
