### ISSUE TITLE
Finish the Precompiler

### ISSUE THREAD

**Issue by ntrupin** [ntrupin/abstractml#43]
**Is your feature request related to a problem? Please describe.**
I am up to my neck in work from both school and my other projects, and need to finish the precompiler.

**Describe the solution you'd like**
I'm looking for contributors who know or are willing to learn the C language to finish putting together the precompiler. I have the framework down already, but many of the tags are missing from it.

**Describe alternatives you've considered**
I don't want to scrap the precompiler, and don't want to leave a half-finished piece of software in the repository. I don't think there are any alternatives.

**Additional context**
If you have any questions, drop me an email at [ntrupin@ntrupin.com](mailto:ntrupin@ntrupin.com) or comment on this issue. Feel free to submit pull requests and start working without leaving me a message first, though.

**Comment by ntrupin** [comment]
**Additional context**
I'm also open to rewrites in other languages! As long as it can be compiled into executables for multiple platforms (Windows, Mac, Linux), whatever works best for you guys is great.

**Comment by Yamboy1** [comment]
What's going on here in terms of implementation? I see we have a basic (experimental) compiler, what progress is happening with it?

**Comment by Yamboy1** [comment]
I also think that it would be best to develop a grammar as well, because it's currently a bit ambiguous as to how the language is meant to work without looking at the source code

**Comment by ntrupin** [comment]
I think this is a good idea. What if, in the process, we replace the `->` indicator? We can make it `|` before attributes and `>` before text, for example.

**Now**
```
h1 -> style=“color:red” -> Hello!
h1 -> Hello!
div -> style=“background-color:red”
div
```

**Future?**
```
h1 | style=“color:red” > Hello!
h1 |> Hello!
div | style=“background-color:red”
div
```

**Comment by Yamboy1** [comment]
This would be a good chance to refine the language slightly. Having looked at the language with fresh eyes, I can't tell whether the language wants to be HTML with less noise in the source, or if it's trying to be a different language.

For example, how certain things are left the same as HTML (p / div tags), while the charset/meta tags are more different.
