### ISSUE TITLE
An import tag to import other aml files

### ISSUE THREAD

**Issue by kitaboon** [ntrupin/abstractml#45]
I have an idea, let's add an `import` tag :
```
file1.aml
---

h1 -> My Title
```
```
file2.aml
---

import -> file1
h2 -> My Subtitle
```
## Result :
```html
<h1>My Title</h1>
<h2>My Subtitle</h2>
```

**Comment by ntrupin** [comment]
I like the idea! I’ll get prototyping as soon as I can.

School has been a bit crazy, and this project has been (sadly) inactive, but I’m looking forward to adding new functionality!
